### ISSUE TITLE
New UI: Pasting is broken.

### ISSUE THREAD

**Issue by B94** [henk717/KoboldAI-Client#339]
https://github.com/KoboldAI/KoboldAI-Client/issues/278
> Another update: Pasting can work to some extent, but still requires text to be selected from the click-menu. Pasting now causes posts to be duplicated and merged.

**Comment by ebolam** [comment]
This can "merge" actions, and is somewhat expected behavior. Example:
1. You copy an action's text
2. You, while the action's text is highlighted paste (ctrl+v should be working now)
3. The system will delete the selected text then paste the copied text. Depending on the browsers implementation of editing (chrome/firefox/safari treat it differently) it'll paste the text between chunks. The system will then sweep the text into the previous chunk so it's not outside of a chunk.

What do you mean by duplicate? Can you give steps to reproduce using the sample story with the latest united?

**Comment by B94** [comment]
The top text is what I had originally. Upon copying the word "test" and pasting it, the text appears as shown in the middle: the prior post is duplicated, and it pushes out what should have been the second part ("Please ignore it."). After refreshing, I get what is seen at the bottom, where the duplicate text is gone and the second part still exists, but is no longer considered part of the actual text.
![image](https://user-images.githubusercontent.com/16430833/235277283-453271a5-386a-4d1e-b0f2-ac37ad3d446b.png)
If it helps any, I'm using Firefox.

**Comment by ebolam** [comment]
A potential fix is in. I was unable to exactly get your behavior but did find a similar bug that might have caused what you saw. If you can, can you please test my git's united branch (that's the default) and see if it's fixed?
https://github.com/ebolam/KoboldAI/

You can test it by running the update-koboldai.bat and typing in the above URL instead of 1 or 2.

**Comment by B94** [comment]
I tested using Google Colab, and it seems to be fixed now.

**Comment by B94** [comment]
While the pushed text is gone. Every post is now merged with the prior one upon pasting.
There is also now a line break after pasting that was not originally part of the message.

**Comment by B94** [comment]
[kobold_debug.zip](https://github.com/henk717/KoboldAI/files/11377691/kobold_debug.zip)
Hopefully, this will help.

**Comment by ebolam** [comment]
OK. New fix is in my git if you want to test it. Also if you have actions you took to make it mess up again that would be helpful (like loaded story, copied text "ABCD". Pasted it after word XYZ, or selected words 1-5 and pasted. Even better if it's on the sample story so I can replicate.

**Comment by B94** [comment]
[kobold_debug.zip](https://github.com/henk717/KoboldAI/files/11391215/kobold_debug.zip)
Tested with Colab using Firefox and the bug seems to have gotten worse. I wrote "This is a test message." as my prompt. The first response ended with "What do you want?", to which I replied with "I want to make sure you're alright."
Following the response, I copied the word "you" from my reply and pasted over it. "'re alright." was separated into its own post, which was removed upon refreshing, and the first response was duplicated into the initial prompt.

I don't know the exacts, but it looks like whatever merging that is going on is done in the opposite direction.

**Comment by henk717** [comment]
Since none of this happened in my own testing I wonder if latency is a factor here.
